name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of deployable artifact files
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: The result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
      # secrets:
        #  some-secret:
         # required: false
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifact-name }}
      - name: List my files
        run: ls
      - name: Output information
        run: echo "Deploying ..."
      - name: Set output
        run: echo "step-result=success" >> $GITHUB_OUTPUT
